/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "oauth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

AuthResponse *
request_authorization_1(AuthRequest *argp, CLIENT *clnt)
{
	static AuthResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_authorization,
		(xdrproc_t) xdr_AuthRequest, (caddr_t) argp,
		(xdrproc_t) xdr_AuthResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

AccessResponse *
request_access_token_1(AccessRequest *argp, CLIENT *clnt)
{
	static AccessResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_access_token,
		(xdrproc_t) xdr_AccessRequest, (caddr_t) argp,
		(xdrproc_t) xdr_AccessResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ErrorCode *
validate_action_1(ActionRequest *argp, CLIENT *clnt)
{
	static ErrorCode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, validate_action,
		(xdrproc_t) xdr_ActionRequest, (caddr_t) argp,
		(xdrproc_t) xdr_ErrorCode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
