/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"


void
oauth_prog_1(char *host)
{
	CLIENT *clnt;
	AuthResponse  *result_1;
	AuthRequest  request_authorization_1_arg;
	AccessResponse  *result_2;
	AccessRequest  request_access_token_1_arg;
	ErrorCode  *result_3;
	ActionRequest  validate_action_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = request_authorization_1(&request_authorization_1_arg, clnt);
	if (result_1 == (AuthResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = request_access_token_1(&request_access_token_1_arg, clnt);
	if (result_2 == (AccessResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = validate_action_1(&validate_action_1_arg, clnt);
	if (result_3 == (ErrorCode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	oauth_prog_1 (host);
exit (0);
}
